# openvpn/server.conf — Serveur VPN d'accès distant (exemple pédagogique)
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0

# Ne pousser QUE la route vers le VLAN Serveurs (accès limité, pas de "full tunnel")
push "route 192.168.20.0 255.255.255.0"

# Durcissement
cipher AES-256-GCM
auth SHA256
tls-crypt tls-crypt.key
remote-cert-tls client
duplicate-cn        # à retirer en prod : un certificat unique par utilisateur
keepalive 10 120
persist-key
persist-tun
verb 3
